apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logging
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  # https://github.com/uber-go/zap/blob/aa3e73ec0896f8b066ddf668597a02f89628ee50/config.go
  zap-logger-config: |
    {
      "level": "{{ .Values.logLevel }}",
      "development": false,
      "disableStacktrace": true,
      "disableCaller": true,
      "sampling": {
        "initial": 100,
        "thereafter": 100
      },
      "outputPaths": [{{ include "karpenter.controller.outputPathsList" . }}],
      "errorOutputPaths": [{{ include "karpenter.controller.errorOutputPathsList" . }}],
      "encoding": "{{ .Values.logEncoding }}",
      "encoderConfig": {
        "timeKey": "{{ .Values.encoderConfig.timeKey }}",
        "levelKey": "{{ .Values.encoderConfig.levelKey }}",
        "nameKey": "{{ .Values.encoderConfig.nameKey }}",
        "callerKey": "{{ .Values.encoderConfig.callerKey }}",
        "messageKey": "{{ .Values.encoderConfig.messageKey }}",
        "stacktraceKey": "{{ .Values.encoderConfig.stacktraceKey }}",
        "levelEncoder": "{{ .Values.encoderConfig.levelEncoder }}",
        "timeEncoder": "{{ .Values.encoderConfig.timeEncoder }}"
      }
    }
{{- with .Values.controller.logLevel }}
  loglevel.controller: {{ . | quote }}
{{- end }}
{{- with .Values.webhook.logLevel }}
  loglevel.webhook: {{ . | quote }}
{{- end }}
